var = {"ImageWidth": 474, "ImageHeight": 710, "FaceInfos": [{"X": 186, "Y": 52, "Width": 100, "Height": 126,
                                                             "FaceAttributesInfo": {"Gender": 99, "Age": 30,
                                                                                    "Expression": 80,
                                                                                    "Glass": false, "Pitch": 10,
                                                                                    "Yaw": 0,
                                                                                    "Roll": 1, "Beauty": 68,
                                                                                    "Hat": false,
                                                                                    "Mask": false,
                                                                                    "Hair": {"Length": 1, "Bang": 1,
                                                                                             "Color": 2},
                                                                                    "EyeOpen": true},
                                                             "FaceQualityInfo": {"Score": 0, "Sharpness": 0,
                                                                                 "Brightness": 0,
                                                                                 "Completeness": {"Eyebrow": 0,
                                                                                                  "Eye": 0,
                                                                                                  "Nose": 0, "Cheek": 0,
                                                                                                  "Mouth": 0,
                                                                                                  "Chin": 0}}},
                                                            {"X": 192, "Y": 216, "Width": 90, "Height": 123,
                                                             "FaceAttributesInfo": {"Gender": 0, "Age": 28,
                                                                                    "Expression": 94,
                                                                                    "Glass": false, "Pitch": 20,
                                                                                    "Yaw": 5,
                                                                                    "Roll": 1, "Beauty": 76,
                                                                                    "Hat": false,
                                                                                    "Mask": false,
                                                                                    "Hair": {"Length": 3, "Bang": 1,
                                                                                             "Color": 2},
                                                                                    "EyeOpen": true},
                                                             "FaceQualityInfo": {"Score": 0, "Sharpness": 0,
                                                                                 "Brightness": 0,
                                                                                 "Completeness": {"Eyebrow": 0,
                                                                                                  "Eye": 0,
                                                                                                  "Nose": 0, "Cheek": 0,
                                                                                                  "Mouth": 0,
                                                                                                  "Chin": 0}}},
                                                            {"X": 202, "Y": 391, "Width": 87, "Height": 119,
                                                             "FaceAttributesInfo": {"Gender": 95, "Age": 3,
                                                                                    "Expression": 64,
                                                                                    "Glass": false, "Pitch": 10,
                                                                                    "Yaw": 0,
                                                                                    "Roll": 0, "Beauty": 70,
                                                                                    "Hat": false,
                                                                                    "Mask": false,
                                                                                    "Hair": {"Length": 1, "Bang": 1,
                                                                                             "Color": 1},
                                                                                    "EyeOpen": true},
                                                             "FaceQualityInfo": {"Score": 0, "Sharpness": 0,
                                                                                 "Brightness": 0,
                                                                                 "Completeness": {"Eyebrow": 0,
                                                                                                  "Eye": 0,
                                                                                                  "Nose": 0, "Cheek": 0,
                                                                                                  "Mouth": 0,
                                                                                                  "Chin": 0}}}],
       "FaceModelVersion": "3.0", "RequestId": "2247736b-0a8b-44a2-af8b-a0c258d364ff"}


